### ISSUE TITLE
Riesenia\Cart\Cart::addItem(): Argument #1 ($item) must be of type Riesenia\Cart\CartItemInterface, string given, called in

### ISSUE THREAD

**Issue by alextanasa91** [riesenia/cart#3]
hello there.

when i try to add a product this error shows
Riesenia\Cart\Cart::addItem(): Argument #1 ($item) must be of type Riesenia\Cart\CartItemInterface, string given, called in C:\xampp\htdocs\app\Controllers\Base.php on line 17 

and the line is 

$cart->addItem($anotherProduct="test", 3);

**Comment by segy** [comment]
hello. as it says - it expects CartItemInterface and you are sending "test" there... not sure how I can help here :)
